name: gittuf Verification
on:
  push:
    branches: ['main']
permissions: read-all
jobs:
  gittuf-verify:
    if: github.repository == 'gittuf/gittuf'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@fe9ac76ca1aa34dfebacfdb3e5a7b31bfbff1f1c
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          sleep 10s
          cd gittuf
          gittuf verify-ref main --verbose
